# Generated by Django 4.1.1 on 2022-09-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('현금', 'cash'), ('카드', 'card'), ('무통장 입금', 'cash_transfer')], max_length=20, verbose_name='결제 수단')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produce.production', verbose_name='주문 번호')),
            ],
        ),
    ]
