# Generated by Django 4.1.1 on 2022-09-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('name', models.CharField(max_length=20, verbose_name='상품 이름')),
                ('origin', models.CharField(max_length=20, verbose_name='원산지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='제조 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='유통 기한')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
